vim.opt.relativenumber = true
vim.opt.lazyredraw = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.undofile = true
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 0
vim.opt.shiftwidth = 0
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.inccommand = "nosplit"
vim.opt.completeopt = "menu"
vim.opt.mouse = "a"
vim.opt.list = true
vim.opt.wrap = false
vim.opt.listchars = "eol: ,tab:→ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨"
vim.opt.fillchars = "fold: ,vert:│,eob:~,msgsep:‾"
vim.opt.updatetime = 16
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.foldmethod = "manual"
vim.opt.termguicolors = true
vim.opt.scrolloff = 5
